name: "Package Extension"
on:
  workflow_dispatch:
jobs:
  package:
    name: Package
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Environment
        run: |
          echo "GHCR_USER=${{ github.actor }}" >> $GITHUB_ENV
          echo "GHCR_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build (amd64)
        uses: devcontainers/ci@v0.3
        with:
          push: never
          imageName: live-development-amd64
          platform: linux/amd64
          runCmd: ./bin/build
      - name: Package (amd64)
        run: ./bin/package-platform amd64
      - name: Build (arm64)
        uses: devcontainers/ci@v0.3
        with:
          push: never
          imageName: live-development-arm64
          platform: linux/arm64
          runCmd: ./bin/build
      - name: Package (arm64)
        run: ./bin/package-platform arm64
      - name: Package (manifest)
        run: ./bin/package
